name: Terraform CI

on:
  # Events/Trigger the workflow
  workflow_dispatch:

jobs:
  terraform:

    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Initialize Terraform
        run: terraform init
