name: Terraform Destroyer

on:
  # Events/Trigger the workflow
  workflow_dispatch:

jobs:
  terraform:

    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Initialize Terraform
        run: terraform init

      - name: Destroy Terraform
        run: terraform destroy -auto-approve